### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by AliSaadatV** [TencentAI4S/CD-GPT#4]
Hi

Super cool work!

I was wondering if you're going to release the processed dataset for pretraining, specially paired data (DNA-Protein, mRNA-Protein). 

Thanks

**Comment by HexagonStar** [comment]
Hi Saadat,
Thank you for your interest in our work! Due to the large size of the processed dataset, which is nearly 2T, we are unable to upload and maintain it on our servers. However, we will promptly make the download links for the raw data and the processing scripts available to ensure the reproducibility of our work. Should you have any further questions regarding data processing, please feel free to raise them then.

**Comment by AliSaadatV** [comment]
Thanks a lot! That would be great.
